server:
    port: 8761
spring:
    application:
        name: eurekaserver
eureka:
    instance:
       hostname: 192.168.96.189
       prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        registerWithEureka: false
        fetchRegistry: false